import "./globals.css";
import { Appprovider } from "./contextapi/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Appprovider>{children}</Appprovider>
      </body>
    </html>
  );
}
